[tools]
selene = { source = "Kampfkarren/selene", version = "x" }
rojo = { source = "rojo-rbx/rojo", version = "7" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.1" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
stylua = { github = "JohnnyMorganz/StyLua", version = "0.13" }
darklua = { gitlab = "seaofvoices/darklua", version = "0.7.0" }